### ISSUE TITLE
Some PDF conversions giving unstructured data

### ISSUE THREAD

**Issue by jgeorge97** [jgeorge97/dam-water-level-app-backend#1]
Some of the pdf's converted to JSON gives the data in an unstructured data, maybe it could be a bug in the pdf-table-extractor npm package. Need to fix this.

**Comment by jgeorge97** [comment]
![bug](https://user-images.githubusercontent.com/26036060/138211598-613a0bec-8165-4398-9200-72102d6e69bf.png)
[KSEB-SITE_07-AM-1.pdf](https://github.com/jgeorge97/dam-water-level-app-backend/files/7385950/KSEB-SITE_07-AM-1.pdf)
Here is the bug & the pdf causing the bug, FYI

**Comment by kishorviswanathan** [comment]
PR #3 partially fixes this issue. 

Above PDF rendered using the given changes.
![image](https://user-images.githubusercontent.com/11171849/138514797-19057b69-40a8-484b-86a2-4c52120cfff4.png)
